name: Request for a new unit
description: Use this form to suggest a new unit be added to UCUM. We may follow up with a request for more information. Please use English (US) as the language for all descriptive text.
labels: ["⏱️evaluating"]
type: "unit"
body:
  - type: input
    id: display-name
    attributes:
      label: Name of unit
      description: Enter the full name of the unit, e.g., meter, quart, British thermal unit, degree Celsius.
    validations:
      required: true
  - type: input
    id: kind-of-quantity
    attributes:
      label: Kind of quantity
      description: Enter the property the unit is measuring, e.g., length, fluid volume, energy, temperature.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the use of this unit. Is it specific to a particular industry or jurisdiction? We encourage you to include URLs to references.
    validations:
      required: true
  - type: dropdown
    id: metric
    attributes:
      label: Metric
      description: Indicate if this unit is metric, i.e., it may be prefixed with the standard metric prefixes (e.g., milli-, centi-, deci-) in Section 4.1 of the specification.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: cs-unit
    attributes:
      label: Unit (case sensitive)
      description: Following Section 2 [Grammar of Units and Unit Terms](https://ucum.org/ucum#section-Grammar-of-Units-and-Unit-Terms) in the specification, how should this unit be referenced in case-sensitive ASCII characters?
    validations:
      required: true
  - type: input
    id: ci-unit
    attributes:
      label: Unit (case insensitive)
      description: In the context of the above, how should this unit be referenced in case-insensitive ASCII characters, i.e. ALL CAPS?
    validations:
      required: true
  - type: input
    id: print
    attributes:
      label: Print display of unit
      description: The accepted display of the unit in most contexts, e.g, m, btu, °C.
    validations:
      required: false
  - type: input
    id: def-unit
    attributes:
      label: Definition unit
      description: This unit is used in conjunction with the following value. Indicate which other UCUM unit shall be used to define this new unit, e.g., an inch is defined in terms of cm, a foot is defined in terms of [in_i].
    validations:
      required: true
  - type: input
    id: def-value
    attributes:
      label: Definition value
      description: This value is used in conjunction with the previous unit. Indicate the value used to define the new unit, e.g., an inch is equal to 2.54 (cm), a foot is 12 (inches) [in_i].
    validations:
      required: true
  - type: input
    id: notes
    attributes:
      label: Comments
      description: Include any notes that have not been captured in previous items.
    validations:
      required: false
